### ISSUE TITLE
https://github.com/wingjay/WJMagicCurveView

### ISSUE THREAD

**Issue by leerduo** [zhangyuChen1991/MagicLine#1]
https://github.com/wingjay/WJMagicCurveView

**Comment by zhangyuChen1991** [comment]
当初确是看wingjay同学的博客知道的这个创意，最初出自OF COURSE的创意编程。这是我9月练手实践的时候写的了，我也看了wingjay和cjj各实现了一套，原理都是一样的。我会在README介绍里添加上wingjay的项目地址并说明出处。最后，我只是推广下我觉得有意思的东西，跟wingjay他们一样，并无任何恶意。
